### ISSUE TITLE
would be nice haveing a Table BBCode for this mod.

### ISSUE THREAD

**Issue by raykai** [martec/Rin-Editor_for_phpBB#22]
Hi, im looking for a Table BBCode to use with your mod. i think this would be useful as i haven't found a working Table BBCode for phpbb. so i was wondering if you could add one on this mod.

**Comment by 7starsone** [comment]
Hello, I really need it too...

also posted on the phpbb forum about this
please help, thanks

**Comment by martec** [comment]
Hi,

Unfortunately I will not support the table plugin. Because bbcode conversion does not work correctly.

**Comment by 7starsone** [comment]
> Because bbcode conversion does not work correctly.

Please, can you explain why in detail? 
I noticed that it correctly adds the button and displays the table, that is editable in the message box but then it doesn't convert to bbcode when submit.

So, at least, Is there a guideline to submit the form (or preview) trying to convert the table in bbcode?

Thank you

**Comment by martec** [comment]
> Please, can you explain why in detail?

Because BBCode plugin of CKEditor doesn't support table plugin.

**Comment by 7starsone** [comment]
ok, you could do it easily and it would be a great feature.
- Build from source (instead of minify), adding the bbcode plugin to the left as component
- Change on bbcode/plugin.js

`var bbcodeMap = { b: 'strong', u: 'u', i: 'em', color: 'span', size: 'span', quote: 'blockquote', code: 'code', url: 'a', email: 'span', img: 'span', '*': 'li', list: 'ol', table: 'table', tr: 'tr', td: 'td', th: 'th' },`

`convertMap = { strong: 'b', b: 'b', u: 'u', em: 'i', i: 'i', code: 'code', li: '*', table: 'table', tr: 'tr', th: 'th', td: 'td' },`
you could even add **tbody**, but don't know if really useful.

- Obviously, the users need to add their custom bbcodes for [table] [tr] [th] [td], even if not added to the editor

Please, test it on the ckeditor samples page, then when you consider it good, you can even minify your code and put it back as phpbb plugin.

Hope this helps
Kind Regards

**Comment by martec** [comment]
Please do not insist on this.
This raises several compatibility issues that I will never support.
if you need this, you will have to do it on your own.

**Comment by 7starsone** [comment]
@martec IMO there's no compatibility issue, unless you don't explain. And if you don't explain, there's no issue. Maybe compatibility with **your** code? If so, the code is wrong, make it easier. At the moment, I think that you don't want to do it, that's easy. Nevermind, so your users will have to manually write a table (in 2017 almost 18), a **standard** feature, unless there are children only who write through  the editor. Just imagine a table with 10 rows 10 columns (even little). Wow, what fun with that looooong piece of text! 😆
